### ISSUE TITLE
UDP link local: (not bound)

### ISSUE THREAD

**Issue by flammable-gel** [alturismo/xteve_vpn#2]
hi, from the xteve container logs I see that xteve cannot connect to the vpn and tries again several times. i think the problem is "UDP link local: (not bound)" but i don't know how to fix it.
Thanks for the support.

OT: Discord link not working.
OT2: I'm sorry I can't get github's insert code function to work.

`Wed Nov 25 17:49:31 2020 UDP link remote: [AF_INET]78.47.208.25:4000

Wed Nov 25 17:49:31 2020 TLS: Initial packet from [AF_INET]78.47.208.25:4000, sid=f3cd9a02 25ffdf82

Wed Nov 25 17:49:31 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this

Wed Nov 25 17:49:31 2020 VERIFY OK: depth=2, C=MY, ST=Wilayah Persekutuan, L=Labuan, O=eVenture Limited, OU=Certificate Authority, CN=Hide.Me Root CA

Wed Nov 25 17:49:31 2020 VERIFY OK: depth=1, C=MY, ST=Wilayah Persekutuan, L=Labuan, O=eVenture Limited, OU=Certificate Authority, CN=Hide.Me Server CA #1

Wed Nov 25 17:49:31 2020 VERIFY KU OK

Wed Nov 25 17:49:31 2020 Validating certificate extended key usage

Wed Nov 25 17:49:31 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication

Wed Nov 25 17:49:31 2020 VERIFY EKU OK

Wed Nov 25 17:49:31 2020 VERIFY X509NAME OK: C=MY, ST=Wilayah Persekutuan, L=Labuan, O=eVenture Limited, OU=Certificate Authority, CN=*.hide.me

Wed Nov 25 17:49:31 2020 VERIFY OK: depth=0, C=MY, ST=Wilayah Persekutuan, L=Labuan, O=eVenture Limited, OU=Certificate Authority, CN=*.hide.me

Wed Nov 25 17:49:32 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 8192 bit RSA

Wed Nov 25 17:49:32 2020 [*.hide.me] Peer Connection Initiated with [AF_INET]78.47.208.25:4000

Wed Nov 25 17:49:33 2020 SENT CONTROL [*.hide.me]: 'PUSH_REQUEST' (status=1)

Wed Nov 25 17:49:34 2020 AUTH: Received control message: AUTH_FAILED

Wed Nov 25 17:49:34 2020 SIGTERM[soft,auth-failure] received, process exiting

/config/Frankfurt.ovpn exist

/config/logindata.conf exist

Wed Nov 25 17:49:34 2020 WARNING: file '/config/logindata.conf' is group or others accessible

Wed Nov 25 17:49:34 2020 OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020

Wed Nov 25 17:49:34 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10

Wed Nov 25 17:49:34 2020 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication

Wed Nov 25 17:49:34 2020 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication

Wed Nov 25 17:49:34 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]78.47.208.29:4000

Wed Nov 25 17:49:34 2020 Socket Buffers: R=[212992->212992] S=[212992->212992]

Wed Nov 25 17:49:34 2020 UDP link local: (not bound)

Wed Nov 25 17:49:34 2020 UDP link remote: [AF_INET]78.47.208.29:4000

Wed Nov 25 17:49:40 2020 TLS: Initial packet from [AF_INET]78.47.208.29:4000, sid=4a54f80e 4a0a06a7

Wed Nov 25 17:49:40 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this

Wed Nov 25 17:49:40 2020 VERIFY OK: depth=2, C=MY, ST=Wilayah Persekutuan, L=Labuan, O=eVenture Limited, OU=Certificate Authority, CN=Hide.Me Root CA

Wed Nov 25 17:49:40 2020 VERIFY OK: depth=1, C=MY, ST=Wilayah Persekutuan, L=Labuan, O=eVenture Limited, OU=Certificate Authority, CN=Hide.Me Server CA #1

Wed Nov 25 17:49:40 2020 VERIFY KU OK

Wed Nov 25 17:49:40 2020 Validating certificate extended key usage

Wed Nov 25 17:49:40 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication

Wed Nov 25 17:49:40 2020 VERIFY EKU OK

Wed Nov 25 17:49:40 2020 VERIFY X509NAME OK: C=MY, ST=Wilayah Persekutuan, L=Labuan, O=eVenture Limited, OU=Certificate Authority, CN=*.hide.me

Wed Nov 25 17:49:40 2020 VERIFY OK: depth=0, C=MY, ST=Wilayah Persekutuan, L=Labuan, O=eVenture Limited, OU=Certificate Authority, CN=*.hide.me

Wed Nov 25 17:49:42 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 8192 bit RSA

Wed Nov 25 17:49:42 2020 [*.hide.me] Peer Connection Initiated with [AF_INET]78.47.208.29:4000

Wed Nov 25 17:49:43 2020 SENT CONTROL [*.hide.me]: 'PUSH_REQUEST' (status=1)

Wed Nov 25 17:49:43 2020 AUTH: Received control message: AUTH_FAILED

Wed Nov 25 17:49:43 2020 SIGTERM[soft,auth-failure] received, process exiting

/config/Frankfurt.ovpn exist

/config/logindata.conf exist

Wed Nov 25 17:49:43 2020 WARNING: file '/config/logindata.conf' is group or others accessible

Wed Nov 25 17:49:43 2020 OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020

Wed Nov 25 17:49:43 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10

Wed Nov 25 17:49:43 2020 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication

Wed Nov 25 17:49:43 2020 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication

Wed Nov 25 17:49:43 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]78.47.208.24:4000

Wed Nov 25 17:49:43 2020 Socket Buffers: R=[212992->212992] S=[212992->212992]

Wed Nov 25 17:49:43 2020 UDP link local: (not bound)

Wed Nov 25 17:49:43 2020 UDP link remote: [AF_INET]78.47.208.24:4000

Wed Nov 25 17:49:43 2020 TLS: Initial packet from [AF_INET]78.47.208.24:4000, sid=66a088f2 fd065b51

Wed Nov 25 17:49:43 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this

Wed Nov 25 17:49:43 2020 VERIFY OK: depth=2, C=MY, ST=Wilayah Persekutuan, L=Labuan, O=eVenture Limited, OU=Certificate Authority, CN=Hide.Me Root CA

Wed Nov 25 17:49:43 2020 VERIFY OK: depth=1, C=MY, ST=Wilayah Persekutuan, L=Labuan, O=eVenture Limited, OU=Certificate Authority, CN=Hide.Me Server CA #1

Wed Nov 25 17:49:43 2020 VERIFY KU OK

Wed Nov 25 17:49:43 2020 Validating certificate extended key usage

Wed Nov 25 17:49:43 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication

Wed Nov 25 17:49:43 2020 VERIFY EKU OK

Wed Nov 25 17:49:43 2020 VERIFY X509NAME OK: C=MY, ST=Wilayah Persekutuan, L=Labuan, O=eVenture Limited, OU=Certificate Authority, CN=*.hide.me`

**Comment by alturismo** [comment]
Received control message: AUTH_FAILED ???

**Comment by flammable-gel** [comment]
I didn't understand that you had to register with hide.me and enter your username and password. I solved it by replacing the ovpn file with one provided by my VPN provider and renamed it Frankfurt.
If I can afford to give you some advice I would put a brief intrusion on how to configure the VPN part.
Thank you for making the project public.

**Comment by alturismo** [comment]
overall you are right, point is i wanted to abonden this project as its more or less obsolete as routing a docker through another docker (like ovpn) is pretty simple meanwhile ...

and here is my normal description, u can name your file as you want and use a variable of course

https://github.com/alturismo/ovpn_privoxy

sorry, i may will update at least the readme here as its still more used as i thought.
