### ISSUE TITLE
Remote access not working

### ISSUE THREAD

**Issue by tomas-lejdung** [alturismo/xteve_vpn#3]
I am running the container on an unraid server and cannot access xTeve webUI or the m3u url remotely even though I've opened the port 34400 on my router. I am having no issues accessing any of my other containers running on the same server.

Thanks in advance!

**Comment by alturismo** [comment]
would need a little more info then please

docker run command as sample ?
how you port forwarded ?

i can say it should work flawlessly, recommended by the way is not to open your xteve by port forwarding, rather use a reverse rpoxy with subdomain(s), but thats up to you.

**Comment by tomas-lejdung** [comment]
Sorry for not providing more information. I am simply running the docker template on my Unraid sever without any custom configuration. I have forwarded the ports on my router (Ubiquiti EdgeRouter X) and it works for all my other services.

I will try to run the standard xTeve container without any VPN to see if that works, and then try to route the container traffic through an container with VPN.

**Comment by tomas-lejdung** [comment]
I've managed to set it up with remote proxy, everything works except for streaming the channels. Meaning that I can access the webui and add the m3u and EPG files, but it won't play any channel streams. How should the nginx file look, I cannot find a template config in the SWAG repo.

If there is to any help, I use xTeve as buffer.

**Comment by alturismo** [comment]
subdomain or subfolder setup ?

subdomain doesnt need any specials ...

here is my working nginx config from swag

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name xteve.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_xteve xteve;
        proxy_pass http://$upstream_xteve:34400;
		proxy_buffering off;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $http_connection;
    }
}

**Comment by tomas-lejdung** [comment]
Thank you, I was missing the last three lines! Works like a charm.
